// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC76VhEFNG6Bug6O9lM5xIv6UGEnmeCQJg',
    appId: '1:1081129375245:web:9e4a09d07826e6dfab2744',
    messagingSenderId: '1081129375245',
    projectId: 'group3-challenge-1',
    authDomain: 'group3-challenge-1.firebaseapp.com',
    storageBucket: 'group3-challenge-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvvkb8unTjBpY_2FZ7t3UBEX9cxDicSk',
    appId: '1:1081129375245:android:23f7615ed812fbbdab2744',
    messagingSenderId: '1081129375245',
    projectId: 'group3-challenge-1',
    storageBucket: 'group3-challenge-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Oo7zVjEP1VSaF3DURqNOkQUVClllrsI',
    appId: '1:1081129375245:ios:382cd53457fb67f6ab2744',
    messagingSenderId: '1081129375245',
    projectId: 'group3-challenge-1',
    storageBucket: 'group3-challenge-1.firebasestorage.app',
    iosBundleId: 'com.example.challenge1Group3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Oo7zVjEP1VSaF3DURqNOkQUVClllrsI',
    appId: '1:1081129375245:ios:382cd53457fb67f6ab2744',
    messagingSenderId: '1081129375245',
    projectId: 'group3-challenge-1',
    storageBucket: 'group3-challenge-1.firebasestorage.app',
    iosBundleId: 'com.example.challenge1Group3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC76VhEFNG6Bug6O9lM5xIv6UGEnmeCQJg',
    appId: '1:1081129375245:web:6149698af970dedeab2744',
    messagingSenderId: '1081129375245',
    projectId: 'group3-challenge-1',
    authDomain: 'group3-challenge-1.firebaseapp.com',
    storageBucket: 'group3-challenge-1.firebasestorage.app',
  );
}
